model:
  class_path: pruning_playground.models.TorchvisionWrapper
  init_args:
    model_name: densenet121
    pretrained: True
    learning_rate: 0.001
    momentum: 0.9
    weight_decay: 0.00002
    norm_weight_decay: 0.0
    label_smoothing: 0.1
    pruning_ratio: 0.3
    pruning_indices_path: "datasets/pruning_indices_densenet121_0.3.pth"

trainer:
  logger:
    - class_path: pruning_playground.utils.logger.WandbLogger
      init_args:
        project: pruning-playground
        entity: viv
        name: DenseNet121-GFI-AP
        notes: "DenseNet121 GFI-AP"
        tags: ["DenseNet121", "GFI-AP"]
        save_code: True
