model:
  class_path: pruning_playground.models.TorchvisionWrapper
  init_args:
    model_name: efficientnet_b0
    pretrained: True
    learning_rate: 0.008
    momentum: 0.9
    weight_decay: 0.00002
    norm_weight_decay: 0.0
    label_smoothing: 0.1
    pruning_ratio: 0.3
    pruning_indices_path: "datasets/pruning_indices_efficientnet_b0_0.3.pth"

trainer:
  logger:
    - class_path: pruning_playground.utils.logger.WandbLogger
      init_args:
        project: pruning-playground
        entity: ziyuan_c
        name: EfficientNet-b0-GFI-AP
        notes: "EfficientNet-b0 GFI-AP"
        tags: ["EfficientNet-b0", "GFI-AP"]
        save_code: True
