model:
  class_path: pruning_playground.models.TorchvisionWrapper
  init_args:
    model_name: inception_v3
    pretrained: True
    learning_rate: 0.001
    momentum: 0.9
    weight_decay: 0.00002
    norm_weight_decay: 0.0
    label_smoothing: 0.1
    pruning_ratio: 0.3
    pruning_indices_path: "datasets/pruning_indices_inception_v3_0.3.pth"

trainer:
  max_epochs: 30
  accelerator: "gpu"
  devices: 1

  logger:
    - class_path: pruning_playground.utils.logger.WandbLogger
      init_args:
        project: pruning-playground
        entity: viv
        name: Inception-v3-GFI-AP
        notes: "Inception-v3 GFI-AP"
        tags: ["Inception-v3", "GFI-AP"]
        save_code: True
  callbacks:
    - class_path: RichProgressBar
      init_args:
        leave: True
    - class_path: ModelCheckpoint
      init_args:
        filename: "epoch_{epoch:03d}_acc1_{val/acc1:.02f}"
        auto_insert_metric_name: False
        save_top_k: -1
        every_n_epochs: 1

  default_root_dir: wandb

seed_everything: 23333
