model:
  class_path: pruning_playground.models.TorchvisionWrapper
  init_args:
    model_name: inception_v3
    pretrained: True
    learning_rate: 0.008
    momentum: 0.9
    weight_decay: 0.00002
    norm_weight_decay: 0.0
    label_smoothing: 0.1
    pruning_ratio: 0.3
    pruning_indices_path: "datasets/pruning_indices_inception_v3_0.3.pth"

trainer:
  logger:
    - class_path: pruning_playground.utils.logger.WandbLogger
      init_args:
        project: pruning-playground
        entity: ziyuan_c
        name: Inception-v3-GFI-AP
        notes: "Inception-v3 GFI-AP"
        tags: ["Inception-v3", "GFI-AP"]
        save_code: True
